### ISSUE TITLE
[LOGIN]: Splash

### ISSUE THREAD

**Issue by andreinamago** [falabella-apps/falabella-seguros-peru-android#1]
Generar Splash dentro de la app:

- [x] Fondo color verde
- [x] ícono SF

**Comment by tolmachevroman** [comment]
![device-2016-11-16-164345](https://cloud.githubusercontent.com/assets/560815/20362929/fce0615c-ac1b-11e6-9978-39033c9e78d7.png)

**Comment by rafaelcs** [comment]
tested
