### ISSUE TITLE
[LOGIN]: Ingreso DNI

### ISSUE THREAD

**Issue by andreinamago** [falabella-apps/falabella-seguros-peru-android#3]
Se debe crear la siguiente pantalla:

**Referencia ingreso de DNI:**

- [x] Btn atrás
- [x] Logo centrado
- [x] Texto "Ingresa tu DNI"
- [x] Btn Continuar

**Posterior al ingreso de DNI:**

- [x] Btn atrás
- [x] Logo centrado
- [x] Check de Verificación en color verde
- [x] Línea de ingreso de DNI en color verde
- [x]  Texto "Ingresa tu DNI"
- [x] Btn Continuar

**Comment by tolmachevroman** [comment]
@andreinamago ¿Cuál sería el formato del DNI peruano?

**Comment by andreinamago** [comment]
@tolmachevroman el mismo que se usa en BF Perú

**Comment by tolmachevroman** [comment]
![device-2016-11-17-115357](https://cloud.githubusercontent.com/assets/560815/20393960/a504ddfe-acbc-11e6-9b0e-13f7cdd0165d.png)

![device-2016-11-17-115410](https://cloud.githubusercontent.com/assets/560815/20393961/a7a69df4-acbc-11e6-96bb-d1b28c229369.png)

![device-2016-11-17-115420](https://cloud.githubusercontent.com/assets/560815/20393967/ab766324-acbc-11e6-89cf-029f837e041b.png)

**Comment by andreinamago** [comment]
@tolmachevroman Formato DNI--> El formato de DNI es alfanumérico y con 8 digitos. No se separa por puntos ni guiones.

**Comment by tolmachevroman** [comment]
@andreinamago Lo voy a hacer alfanumérico entonces.

**Comment by tolmachevroman** [comment]
@andreinamago Listo

![device-2016-11-24-160251](https://cloud.githubusercontent.com/assets/560815/20608432/b3db927e-b260-11e6-8897-b9e13234854f.png)

**Comment by rafaelcs** [comment]
tested
