### ISSUE TITLE
[LOGIN]: Bienvenido

### ISSUE THREAD

**Issue by andreinamago** [falabella-apps/falabella-seguros-peru-android#8]
Se debe crear una pantalla:

- [x] Logo SF centrado
- [x] Texto en Bold fijo: "Bienvenido"
- [x] Texto en Bold fijo: "Nombre Cliente"
- [x] Texto en fijo: "Gracias por completar la verificación"
- [x] IMG
- [x] Btn "Continuar" en verde

**Comment by tolmachevroman** [comment]
![device-2016-11-18-093055](https://cloud.githubusercontent.com/assets/560815/20430214/df51a360-ad71-11e6-91a2-1aee81b4ac9d.png)

**Comment by andreinamago** [comment]
@tolmachevroman por fa, eliminar logo 

https://www.dropbox.com/s/wndiac321csad3f/login%2006.jpg?dl=0

**Comment by tolmachevroman** [comment]
@andreinamago Listo

![device-2016-11-24-161821](https://cloud.githubusercontent.com/assets/560815/20608553/ab473626-b261-11e6-9c02-258b28f9d5b9.png)

**Comment by rafaelcs** [comment]
tested
