### ISSUE TITLE
Update Launcher

### ISSUE THREAD

**Issue by andreinamago** [falabella-apps/falabella-seguros-peru-android#9]
Por favor, se debe actualizar Launcher con la siguiente imagen.
![icon_pe](https://cloud.githubusercontent.com/assets/18466594/20605189/d5cb2bfa-b248-11e6-8c0b-bd9d205959b1.png)

**Comment by tolmachevroman** [comment]
![device-2016-11-24-133335](https://cloud.githubusercontent.com/assets/560815/20605534/9f168c4c-b24a-11e6-8944-41776bc0eacb.png)

**Comment by rafaelcs** [comment]
tested
